age = int(input('enter the age of the participant: '))
ticket =input('enter the ticket: ')
regNo= int(input('enter college reg.no :  '))
print ('the participant eligible for entry: ',age >= 18 and ticket != None)
print ('participant eligible for VIP Entry: ', 'vip' in ticket )
paymentUid= int(input("Enter the payment Uid: "))
print('Is the registration complete: ', paymentUid > 0  and regNo> 0)
registration =input('Enter Yes or no ')
print('Is the registration active: ', registration == 'yes' or 'YES')